//! Cross-provider handoff (live): contexts generated by one provider/model
//! must be accepted by every other.
//!
//! Port of hoocode `packages/ai/test/cross-provider-handoff.test.ts`
//! (v0.5.89). Needs network and provider keys in the environment; OAuth-only
//! providers (openai-codex, github-copilot) are skipped until their OAuth
//! crates land (8.4a, 8.4b). Run with `cargo test -p hoocode-ai-registry --test
//! cross_provider_handoff -- --ignored --nocapture`.

use hoocode_ai_registry::complete_simple;
use hoocode_ai_types::{
    AssistantMessage, Content, Context, Message, Model, SimpleStreamOptions, StopReason,
    TextContent, ThinkingLevel, Tool, ToolResultMessage, UserMessage,
};
use serde_json::json;

/// `(provider, model, label, api override)`.
const PROVIDER_MODEL_PAIRS: &[(&str, &str, &str, Option<&str>)] = &[
    (
        "anthropic",
        "claude-sonnet-4-5",
        "anthropic-claude-sonnet-4-5",
        None,
    ),
    (
        "google",
        "gemini-3-flash-preview",
        "google-gemini-3-flash-preview",
        None,
    ),
    (
        "openai",
        "gpt-4o-mini",
        "openai-completions-gpt-4o-mini",
        Some("openai-completions"),
    ),
    ("openai", "gpt-5-mini", "openai-responses-gpt-5-mini", None),
    (
        "openai-codex",
        "gpt-5.3-codex",
        "openai-codex-gpt-5.3-codex",
        None,
    ),
    (
        "github-copilot",
        "gpt-5.3-codex",
        "copilot-gpt-5.3-codex",
        None,
    ),
    (
        "github-copilot",
        "gpt-5.1-codex",
        "copilot-gpt-5.1-codex",
        None,
    ),
    (
        "github-copilot",
        "gemini-3-flash-preview",
        "copilot-gemini-3-flash-preview",
        None,
    ),
    (
        "github-copilot",
        "grok-code-fast-1",
        "copilot-grok-code-fast-1",
        None,
    ),
    ("xai", "grok-code-fast-1", "xai-grok-code-fast-1", None),
    ("cerebras", "zai-glm-4.7", "cerebras-zai-glm-4.7", None),
    (
        "nvidia",
        "meta/llama-3.3-70b-instruct",
        "nvidia-llama-3.3-70b",
        None,
    ),
    ("groq", "openai/gpt-oss-120b", "groq-gpt-oss-120b", None),
    (
        "huggingface",
        "moonshotai/Kimi-K2.5",
        "huggingface-kimi-k2.5",
        None,
    ),
    ("together", "moonshotai/Kimi-K3", "together-kimi-k3", None),
    (
        "kimi-coding",
        "kimi-for-coding",
        "kimi-coding-for-coding",
        None,
    ),
    ("minimax", "MiniMax-M2.7", "minimax-m2.7", None),
    ("minimax-cn", "MiniMax-M2.7", "minimax-m2.7", None),
    ("opencode", "big-pickle", "zen-big-pickle", None),
    (
        "opencode",
        "claude-sonnet-4-5",
        "zen-claude-sonnet-4-5",
        None,
    ),
    ("opencode", "gemini-3-flash", "zen-gemini-3-flash", None),
    ("opencode", "glm-4.7-free", "zen-glm-4.7-free", None),
    ("opencode", "gpt-5.3-codex", "zen-gpt-5.3-codex", None),
    (
        "opencode",
        "minimax-m2.1-free",
        "zen-minimax-m2.1-free",
        None,
    ),
    ("opencode-go", "kimi-k3", "go-kimi-k3", None),
    ("opencode-go", "minimax-m2.7", "go-minimax-m2.7", None),
    ("xiaomi", "mimo-v2.5-pro", "xiaomi-mimo-v2.5-pro", None),
    (
        "xiaomi-token-plan-cn",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-cn-mimo-v2.5-pro",
        None,
    ),
    (
        "xiaomi-token-plan-ams",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-ams-mimo-v2.5-pro",
        None,
    ),
    (
        "xiaomi-token-plan-sgp",
        "mimo-v2.5-pro",
        "xiaomi-token-plan-sgp-mimo-v2.5-pro",
        None,
    ),
];

fn test_tool() -> Tool {
    Tool {
        defer_loading: None,
        name: "double_number".into(),
        description: "Doubles a number and returns the result".into(),
        parameters: json!({
            "type": "object",
            "properties": {"value": {"type": "number", "description": "A number to double"}},
            "required": ["value"]
        }),
    }
}

fn user(text: &str) -> Message {
    Message::User(UserMessage {
        content: vec![Content::Text(TextContent::new(text))].into(),
        timestamp: 0,
    })
}

fn model_for(provider: &str, id: &str, api: Option<&str>) -> Option<Model> {
    let mut model = hoocode_ai_models::get_model(provider, id)?.clone();
    if let Some(api) = api {
        model.api = api.into();
    }
    Some(model)
}

fn options(model: &Model, api_key: &str) -> SimpleStreamOptions {
    SimpleStreamOptions {
        api_key: Some(api_key.into()),
        reasoning: model.reasoning.then_some(ThinkingLevel::High),
        ..Default::default()
    }
}

fn complete(model: &Model, context: Context, api_key: &str) -> AssistantMessage {
    let runtime = tokio::runtime::Runtime::new().unwrap();
    let opts = options(model, api_key);
    runtime.block_on(async {
        match complete_simple(model.clone(), context, opts).await {
            Ok(m) => m,
            Err(e) => AssistantMessage {
                stop_reason: StopReason::Error,
                error_message: Some(e.to_string()),
                ..Default::default()
            },
        }
    })
}

/// `generateContext`: a real exchange with a tool call and its result.
fn generate_context(model: &Model, api_key: &str) -> Option<Vec<Message>> {
    let prompt = user("Please double the number 21 using the double_number tool.");
    let first = complete(
        model,
        Context::new(
            "You are a helpful assistant. Use the provided tool to complete the task.".into(),
            vec![prompt.clone()],
            vec![test_tool()],
        ),
        api_key,
    );
    if first.stop_reason == StopReason::Error {
        eprintln!("  Initial request error: {:?}", first.error_message);
        return None;
    }
    let Some(call) = first.content.iter().find_map(|c| match c {
        Content::ToolCall(tc) => Some(tc.clone()),
        _ => None,
    }) else {
        return Some(vec![prompt, Message::Assistant(first)]);
    };
    let result = Message::ToolResult(ToolResultMessage {
        tool_call_id: call.id.clone(),
        tool_name: call.name.clone(),
        content: vec![Content::Text(TextContent::new("42"))],
        details: None,
        is_error: false,
        timestamp: 0,
    });
    let messages = vec![prompt, Message::Assistant(first), result];
    let last = complete(
        model,
        Context::new(
            "You are a helpful assistant.".into(),
            messages.clone(),
            vec![test_tool()],
        ),
        api_key,
    );
    if last.stop_reason == StopReason::Error {
        eprintln!("  Final request error: {:?}", last.error_message);
        return None;
    }
    let mut messages = messages;
    messages.push(Message::Assistant(last));
    Some(messages)
}

#[test]
#[ignore = "live: needs provider API keys and network"]
fn cross_provider_handoff() {
    let mut contexts: Vec<(&str, Model, String, Vec<Message>)> = Vec::new();
    for (provider, id, label, api) in PROVIDER_MODEL_PAIRS {
        let Some(api_key) = hoocode_ai_env::get_env_api_key(provider) else {
            eprintln!("[{label}] Skipping - no auth for {provider}");
            continue;
        };
        let Some(model) = model_for(provider, id, *api) else {
            eprintln!("[{label}] Model not found");
            continue;
        };
        eprintln!("[{label}] Generating fixture...");
        match generate_context(&model, &api_key) {
            Some(messages) if messages.len() >= 4 => {
                contexts.push((label, model, api_key, messages))
            }
            _ => eprintln!("[{label}] Failed to generate fixture, skipping"),
        }
    }
    assert!(
        contexts.len() >= 2,
        "need at least 2 fixtures, got {}",
        contexts.len()
    );

    let mut failures = Vec::new();
    for (label, model, api_key, _) in &contexts {
        let mut messages: Vec<Message> = contexts
            .iter()
            .filter(|(other, ..)| other != label)
            .flat_map(|(.., m)| m.clone())
            .collect();
        messages.push(user(
            "Great, thanks for all that help! Now just say 'Hello, handoff successful!' to confirm you received everything.",
        ));
        let response = complete(
            model,
            Context::new(
                "You are a helpful assistant.".into(),
                messages,
                vec![test_tool()],
            ),
            api_key,
        );
        if response.stop_reason == StopReason::Error {
            eprintln!("[Target: {label}] FAILED: {:?}", response.error_message);
            failures.push(format!("{label}: {:?}", response.error_message));
        } else {
            eprintln!("[Target: {label}] SUCCESS");
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
