//! Model catalog data, generated from models.dev by the `models-sync` tool
//! (`crates/hoocode-models-sync`). Regenerated by a scheduled workflow and
//! embedded at build time; see the crate README.

/// hoocode's LLM models: a JSON array of `Model` objects, grouped by provider.
/// Written by `models-sync`; hand edits go in `data/overrides.json`.
pub const MODELS_JSON: &str = include_str!("../data/models.json");

/// hoocode's image models, in the same shape. Not generated (models.dev lists
/// no image models), so this file is maintained by hand.
pub const IMAGE_MODELS_JSON: &str = include_str!("../data/image-models.json");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_files_are_json_arrays() {
        for data in [MODELS_JSON, IMAGE_MODELS_JSON] {
            assert!(data.trim_start().starts_with('['));
            assert!(data.trim_end().ends_with(']'));
        }
    }
}
