#!/usr/bin/env python3
"""TS test port ledger (migration task 13.4): every hoocode test file at the pin,
classified as ported / equivalent / n.a. / pending / review.

Sources, first match wins:
  1. migration/ts-tests-overrides.json  curated rules (fnmatch globs), each with a note
  2. ledger tasks' `ts_tests`            ported when an owning task is done/l1_done,
                                         else pending on that task
  3. a Rust source under crates/ that names the file (ported tests cite their TS file)
  4. otherwise `review`                  task 13.4b resolves these

    ts_tests.py generate [--check-fresh]   write migration/ts-tests.json (or fail if stale)
    ts_tests.py status                     counts per status and package
    ts_tests.py list [status]              the files with that status (default review)
    ts_tests.py check [glob...]            fail while any file (matching a glob) is `review`
                                           or ts-tests.json is stale

Needs the pinned hoocode checkout (migration/tui-parity/setup_hoocode.sh).
"""

from __future__ import annotations

import collections
import fnmatch
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PIN = Path(os.environ.get("HOOCODE_PIN_DIR", ROOT / "target" / "hoocode-pin"))
LEDGER = ROOT / "migration" / "ledger.json"
OVERRIDES = ROOT / "migration" / "ts-tests-overrides.json"
OUT = ROOT / "migration" / "ts-tests.json"
STATUSES = ("ported", "equivalent", "n.a.", "pending", "review")
DONE = ("done", "l1_done")


def ts_test_files() -> list[str]:
    if not (PIN / "packages").exists():
        sys.exit(f"pinned hoocode not found at {PIN}; run migration/tui-parity/setup_hoocode.sh")
    files = []
    for dirpath, dirnames, filenames in os.walk(PIN / "packages"):
        dirnames[:] = [d for d in dirnames if d != "node_modules"]
        for name in filenames:
            if name.endswith((".test.ts", ".test.tsx")):
                files.append(str(Path(dirpath, name).relative_to(PIN)))
    return sorted(files)


def rust_citations() -> dict[str, list[str]]:
    """basename -> Rust files under crates/ that mention it."""
    cites: dict[str, list[str]] = collections.defaultdict(list)
    for path in sorted((ROOT / "crates").rglob("*.rs")):
        if "target" in path.parts:
            continue
        text = path.read_text(errors="replace")
        if ".test.ts" not in text:
            continue
        for token in set(t for t in text.replace("`", " ").replace("(", " ").replace(")", " ").split() if ".test.ts" in t):
            base = token.strip("\"',.;:").split("/")[-1]
            cites[base].append(str(path.relative_to(ROOT)))
    return cites


def owners(ledger: dict, path: str) -> list[tuple[str, str]]:
    found = []
    for task in ledger["tasks"]:
        for pattern in task.get("ts_tests", []):
            if path == pattern or fnmatch.fnmatch(path, pattern) or (pattern.endswith("/") and path.startswith(pattern)):
                found.append((task["id"], task["status"]))
                break
    return found


def classify() -> dict:
    ledger = json.loads(LEDGER.read_text())
    rules = json.loads(OVERRIDES.read_text())["rules"]
    cites = rust_citations()
    tests = {}
    for path in ts_test_files():
        entry: dict
        rule = next((r for r in rules if fnmatch.fnmatch(path, r["match"])), None)
        own = owners(ledger, path)
        cited = sorted(set(cites.get(Path(path).name, [])))
        if rule is not None:
            entry = {"status": rule["status"], "note": rule["note"]}
            if rule.get("task"):
                entry["tasks"] = [rule["task"]]
        elif own:
            done = [t for t, s in own if s in DONE]
            entry = {"status": "ported", "tasks": done} if done else {"status": "pending", "tasks": [t for t, _ in own]}
        elif cited:
            entry = {"status": "ported"}
        else:
            entry = {"status": "review"}
        if cited:
            entry["rust"] = cited
        tests[path] = entry
    summary = collections.Counter(e["status"] for e in tests.values())
    return {
        "_comment": "Generated by migration/ts_tests.py from ledger.json ts_tests, Rust citations and ts-tests-overrides.json. Do not edit by hand.",
        "pin": ledger["pin"],
        "summary": {s: summary.get(s, 0) for s in STATUSES},
        "tests": tests,
    }


def render(doc: dict) -> str:
    return json.dumps(doc, indent=1, ensure_ascii=False) + "\n"


def load() -> dict:
    return json.loads(OUT.read_text())


def main() -> int:
    args = sys.argv[1:] or ["status"]
    cmd = args[0]
    if cmd == "generate":
        text = render(classify())
        if "--check-fresh" in args:
            if not OUT.exists() or OUT.read_text() != text:
                print("migration/ts-tests.json is stale: run python3 migration/ts_tests.py generate")
                return 1
            print("ts-tests.json is up to date")
            return 0
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}: {json.loads(text)['summary']}")
        return 0
    doc = load()
    if cmd == "status":
        print(f"{len(doc['tests'])} TS test files at hoocode {doc['pin']['hoocode_version']}: {doc['summary']}")
        per = collections.Counter((p.split("/")[1], e["status"]) for p, e in doc["tests"].items())
        for pkg in sorted({p for p, _ in per}):
            print(f"  {pkg:14}", "  ".join(f"{s}={per[(pkg, s)]}" for s in STATUSES if per[(pkg, s)]))
        return 0
    if cmd == "list":
        want = args[1] if len(args) > 1 else "review"
        for p, e in doc["tests"].items():
            if e["status"] == want:
                print(p, *(["(" + ", ".join(e.get("tasks", [])) + ")"] if e.get("tasks") else []))
        return 0
    if cmd == "check":
        fresh = classify()
        if render(fresh) != OUT.read_text():
            print("migration/ts-tests.json is stale: run python3 migration/ts_tests.py generate")
            return 1
        globs = args[1:] or ["*"]
        review = [p for p, e in fresh["tests"].items() if e["status"] == "review" and any(fnmatch.fnmatch(p, g) for g in globs)]
        if review:
            print(f"{len(review)} TS test files still need review:")
            print("\n".join(f"  {p}" for p in review))
            return 1
        print("every matching TS test file is classified")
        return 0
    sys.exit(__doc__)


if __name__ == "__main__":
    sys.exit(main())
