#!/usr/bin/env python3
"""Generate crates/hoocode-code-cli/src/help_text.rs from hoocode's printHelp().

Reads the pinned hoocode (target/hoocode-pin) cli/args.ts, takes the printHelp
template literal, substitutes the config constants with hoocode branding and
emits (text, bold) segments. Re-run after a pin bump:

    python3 migration/tools/gen_help_text.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "target/hoocode-pin/packages/coding-agent/src/cli/args.ts"
OUT = ROOT / "crates/hoocode-code-cli/src/help_text.rs"


def main() -> None:
    src = SRC.read_text()
    start = src.index("console.log(`") + len("console.log(`")
    end = src.index("`);\n}", start)
    t = src[start:end]
    t = t.replace("${chalk.bold(APP_NAME)}", '${chalk.bold("hoocode")}')
    t = t.replace("${extensionFlagsText}", "\x00EXT\x00")
    t = t.replace("${ENV_AGENT_DIR.padEnd(32)}", "CORTEX_CODING_AGENT_DIR".ljust(32))
    t = t.replace("${ENV_SESSION_DIR.padEnd(32)}", "CORTEX_CODING_AGENT_SESSION_DIR".ljust(32))
    t = t.replace("${APP_NAME}", "hoocode").replace("${CONFIG_DIR_NAME}", ".cortexcode")
    # Branding is already hoocode in the TS text. "hooteams" is a separate product and stays.
    t = t.replace(".hoocode", ".cortexcode").replace("HOOCODE_", "CORTEX_")
    # Azure is dropped (decisions-2026-10-08.md): leave its env var lines out of the help.
    t = "\n".join(line for line in t.split("\n") if "AZURE_OPENAI_" not in line)
    parts = re.split(r'\$\{chalk\.bold\("([^"]*)"\)\}', t)
    leftover = [m for p in parts for m in re.findall(r"\$\{[^}]*\}", p)]
    assert not leftover, leftover

    segments = []
    for k, p in enumerate(parts):
        bold = k % 2 == 1
        # Split out the extension-flags slot as its own marker segment.
        for j, piece in enumerate(p.split("\x00EXT\x00")):
            if j:
                segments.append(("", "Ext"))
            if piece:
                segments.append((piece, "Bold" if bold else "Plain"))

    lines = [
        "// @generated by migration/tools/gen_help_text.py from hoocode cli/args.ts",
        "// printHelp() at the pin. Do not edit by hand. Branding: hoocode-ts -> hoocode.",
        "",
        "use crate::help::Seg;",
        "",
        "pub(crate) const HELP_SEGMENTS: &[Seg] = &[",
    ]
    for text, kind in segments:
        lines.append(f"    Seg::Ext," if kind == "Ext" else f"    Seg::{kind}({json.dumps(text, ensure_ascii=False)}),")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
